# Generated by Django 6.0.6 on 2026-06-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Supplier Company or Vendor Name', max_length=255, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='Name of the person you deal with', max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this supplier from dropdowns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
