# Generated by Django 6.0.6 on 2026-06-13 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0004_alter_customer_id_alter_education_id_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units purchased')),
                ('unit_cost_bdt', models.DecimalField(decimal_places=2, help_text='Cost per unit', max_digits=10)),
                ('total_cost_bdt', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('supplier_name', models.CharField(blank=True, help_text='Wholesale supplier name', max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('entry_by', models.ForeignKey(blank=True, help_text='Employee who logged this purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='products.product')),
            ],
        ),
    ]
