# Generated by Django 6.0.6 on 2026-06-13 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_customer_id_alter_education_id_and_more'),
        ('products', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='entry_by',
            field=models.ForeignKey(blank=True, help_text='Employee who logged this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.employee'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(help_text='Product being restocked', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='products.product'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(editable=False, help_text='Auto-generated PUR ID', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_cost_bdt',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Auto-calculated total cost', max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='unit_cost_bdt',
            field=models.DecimalField(decimal_places=2, help_text='Cost price per unit in BDT', max_digits=12),
        ),
    ]
