# Generated by Django 6.0.6 on 2026-06-20 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier_company',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Cash, Bank, Mobile Banking', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost_bdt',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
