# Generated by Django 6.0.6 on 2026-06-14 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_customer_id_alter_education_id_and_more'),
        ('products', '0001_initial'),
        ('purchase', '0002_purchase_remarks_alter_purchase_entry_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='entry_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.employee'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='products.product'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_cost_bdt',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='unit_cost_bdt',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
