# Generated by Django 6.0.6 on 2026-06-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_purchaseorder_supplier_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payable_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(default='Unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14),
        ),
    ]
