# Generated by Django 6.0.6 on 2026-06-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company Name (e.g., Yamaha, Suzuki)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the brand', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
