# Generated by Django 6.0.6 on 2026-06-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='opening_balance',
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(help_text='e.g., 1000 for Cash, 3000 for Capital', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='content_type',
            field=models.CharField(blank=True, help_text="'Capital', 'Expense', 'Payment-IN', etc.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='object_id',
            field=models.CharField(blank=True, help_text='Stores the custom ID e.g., EXP-1234', max_length=50, null=True),
        ),
    ]
