# Generated by Django 6.0.6 on 2026-06-14 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0004_alter_customer_id_alter_education_id_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_bdt', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per unit (Leave blank to use default Product Retail Price)', max_digits=12)),
                ('discount_bdt', models.DecimalField(decimal_places=2, default=0.0, help_text='Total discount given on this sale item', max_digits=10)),
                ('total_price_bdt', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(help_text='Bought by (Customer)', on_delete=django.db.models.deletion.RESTRICT, related_name='purchased_items', to='person.customer')),
                ('employee', models.ForeignKey(blank=True, help_text='Sold by (Employee)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_handled', to='person.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales_history', to='products.product')),
            ],
        ),
    ]
