# Generated by Django 6.0.6 on 2026-06-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='profit_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price_bdt',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
