# Generated by Django 6.0.6 on 2026-06-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_saleitem_profit_bdt_saleorder_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='payable_amount',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='payment_status',
            field=models.CharField(default='Unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14),
        ),
    ]
