# Generated by Django 6.0.6 on 2026-06-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(editable=False, help_text='Auto-generated system ID', max_length=20, unique=True)),
                ('part_number', models.CharField(help_text="Manufacturer's part number (Primary Identifier)", max_length=100, unique=True)),
                ('product_name', models.CharField(help_text='Full descriptive name', max_length=255)),
                ('brand', models.CharField(help_text='Brand (Honda, Yamaha, Bajaj, etc.)', max_length=100)),
                ('category', models.CharField(help_text='Category > Sub-Category hierarchy', max_length=100)),
                ('source', models.CharField(choices=[('Import', 'Import (India)'), ('Local', 'Local Purchase')], default='Local', help_text='Determines pricing rules', max_length=20)),
                ('hs_code', models.CharField(blank=True, help_text='Customs HS code for import', max_length=50, null=True)),
                ('mrp_inr', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum Retail Price in Indian Rupee', max_digits=10)),
                ('mrp_bdt', models.DecimalField(blank=True, decimal_places=2, help_text='MRP converted to BDT', max_digits=10, null=True)),
                ('purchase_cost_bdt', models.DecimalField(decimal_places=2, default=0.0, help_text='Landed cost or local purchase cost', max_digits=10)),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Markup % on INR (for imports)', max_digits=5)),
                ('wholesale_price_bdt', models.DecimalField(decimal_places=2, default=0.0, help_text='Selling price for wholesale dealers', max_digits=10)),
                ('retail_price_bdt', models.DecimalField(decimal_places=2, default=0.0, help_text='Selling price for retail customers', max_digits=10)),
                ('unit', models.CharField(default='piece', help_text='Primary unit (piece, set, box)', max_length=50)),
                ('alternative_units', models.CharField(blank=True, help_text='e.g., 1 box = 12 pieces', max_length=100, null=True)),
                ('barcode', models.CharField(help_text='EAN-13 or custom barcode', max_length=100, unique=True)),
                ('warranty_period', models.IntegerField(default=0, help_text='Warranty period in months')),
                ('vat_code', models.CharField(help_text='Applicable VAT rate code', max_length=50)),
                ('vehicle_compatibility', models.TextField(blank=True, help_text='Make, Model, Year Range (e.g., Honda CB 125, 2018-2024)', null=True)),
                ('min_stock_level', models.IntegerField(default=5, help_text='Reorder alert threshold per warehouse')),
                ('max_stock_level', models.IntegerField(blank=True, help_text='Overstock warning level', null=True)),
                ('reorder_point', models.IntegerField(default=5, help_text='Trigger for purchase requisition')),
                ('product_status', models.CharField(choices=[('Active', 'Active'), ('Discontinued', 'Discontinued'), ('Seasonal', 'Seasonal'), ('Damaged', 'Damaged (slow-moving)')], default='Active', max_length=20)),
                ('damage_discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Special discounted price if damaged', max_digits=10, null=True)),
                ('damage_remark', models.TextField(blank=True, help_text='Reason for discount', null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='product_pics/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='product_pics/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='product_pics/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='product_pics/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='product_pics/')),
            ],
        ),
    ]
