# Generated by Django 6.0.6 on 2026-06-20 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Select the Brand (e.g., Yamaha, Suzuki)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='brand.brand'),
        ),
    ]
