# Generated by Django 6.0.6 on 2026-06-24 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('main_category', models.CharField(choices=[('Salary', 'Employee Salary'), ('Operational', 'Operational Expenses'), ('Loan', 'Loan Payments'), ('Asset', 'Asset Purchase'), ('Others', 'Others')], max_length=50)),
                ('sub_category', models.CharField(choices=[('Basic Pay', 'Basic Pay'), ('Overtime', 'Overtime'), ('Bonus', 'Bonus / Festival Allowance'), ('Advance Salary', 'Advance Salary / Loan Adjustment'), ('Rent', 'Shop / Warehouse Rent'), ('Utility', 'Electricity / Water / Internet'), ('Office Supplies', 'Office Supplies & Stationery'), ('Entertainment', 'Tea / Snacks / Client Entertainment'), ('Transportation', 'Transportation / Conveyance'), ('Maintenance', 'Repairs & Maintenance'), ('Marketing', 'Marketing & Promotions'), ('Bank EMI', 'Bank Loan EMI'), ('Private Loan', 'Private Loan Repayment'), ('Furniture', 'Furniture & Fixtures'), ('IT Equipment', 'Computers & IT Equipment'), ('Tools', 'Tools & Machinery'), ('Miscellaneous', 'Miscellaneous'), ('Donation', 'Donation / Charity'), ('Fines', 'Fines / Penalties')], max_length=50)),
                ('salary_month', models.DateField(blank=True, help_text='If this is a salary, what month is it for?', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('bKash', 'bKash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket'), ('Cheque', 'Cheque')], default='Cash', max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='Bank/Mobile Banking TXN ID. Leave empty if Cash.', max_length=100, null=True)),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee_recipient', models.ForeignKey(blank=True, help_text='Select if Main Category is Salary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_salaries', to='person.employee')),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='person.employee')),
            ],
        ),
    ]
