# Generated by Django 6.0.6 on 2026-06-24 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Owner Investment, Bank Loan', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('source_name', models.CharField(help_text='Name of the owner, bank, or lender', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank Transfer / Cheque'), ('MFS', 'Mobile Financial Service (bKash, Nagad, etc.)')], default='Cash', max_length=20)),
                ('bank_name', models.CharField(blank=True, help_text='e.g., BRAC Bank, City Bank', max_length=100, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mfs_provider', models.CharField(blank=True, choices=[('bKash', 'bKash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket'), ('Upay', 'Upay'), ('Other', 'Other')], max_length=50, null=True)),
                ('mfs_phone_number', models.CharField(blank=True, help_text='e.g., +88017XXXXXXXX', max_length=20, null=True)),
                ('mfs_transaction_id', models.CharField(blank=True, help_text='TrxID', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Any specific notes or terms of the loan/investment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.employee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capitals', to='capital.capitalcategory')),
            ],
        ),
    ]
