# Generated by Django 6.0.6 on 2026-06-23 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0004_alter_customer_id_alter_education_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('Owner Investment', 'Owner Investment (Equity)'), ('Bank Loan', 'Bank Loan (Long-term Liability)'), ('Personal Loan', 'Personal Loan / Borrowing (Short-term)'), ('Other', 'Other Capital Source')], max_length=50)),
                ('source_name', models.CharField(help_text='Name of the owner, bank, or lender', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_date', models.DateField()),
                ('remarks', models.TextField(blank=True, help_text='Any specific notes or terms of the loan/investment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.employee')),
            ],
        ),
    ]
