# Generated by Django 6.0.6 on 2026-06-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='category',
            field=models.CharField(help_text='e.g., Owner Investment, Bank Loan, or any custom category entered by the user', max_length=100),
        ),
    ]
