# Generated by Django 6.0.6 on 2026-06-23 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0002_alter_capital_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Owner Investment, Bank Loan', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='capital',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capitals', to='capital.capitalcategory'),
        ),
    ]
