# Generated by Django 6.0.6 on 2026-06-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0003_capitalcategory_alter_capital_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='capital',
            name='bank_name',
            field=models.CharField(blank=True, help_text='e.g., BRAC Bank, City Bank', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='capital',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='capital',
            name='mfs_phone_number',
            field=models.CharField(blank=True, help_text='e.g., +88017XXXXXXXX', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='capital',
            name='mfs_provider',
            field=models.CharField(blank=True, choices=[('bKash', 'bKash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket'), ('Upay', 'Upay'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='capital',
            name='mfs_transaction_id',
            field=models.CharField(blank=True, help_text='TrxID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='capital',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank Transfer / Cheque'), ('MFS', 'Mobile Financial Service (bKash, Nagad, etc.)')], default='Cash', max_length=20),
        ),
    ]
