import { useState, useEffect } from "react";
import axiosInstance from "../../../api/axios";
import { FiDollarSign, FiTrendingUp, FiBox, FiActivity, FiArrowRight, FiArrowLeft } from "react-icons/fi";

export default function FinancialDashboard() {
  const [accounts, setAccounts] = useState([]);
  const [journalEntries, setJournalEntries] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    fetchFinancialData();
  }, []);

  const fetchFinancialData = async () => {
    try {
      // Fetch both Accounts and Recent Transactions simultaneously
      const [accountsRes, entriesRes] = await Promise.all([
        axiosInstance.get("account/accounts/"),
        axiosInstance.get("account/journal-entries/")
      ]);
      
      setAccounts(accountsRes.data);
      setJournalEntries(entriesRes.data);
      setLoading(false);
    } catch (err) {
      setError("Failed to load financial data. Ensure Django is running.");
      setLoading(false);
    }
  };

  // Helper function to safely get the balance of a specific account code
  const getBalance = (code) => {
    const acc = accounts.find((a) => a.code === code);
    return acc ? parseFloat(acc.balance) : 0;
  };

  if (loading) return <div className="text-gray-500 font-medium p-6 animate-pulse">Loading Financials...</div>;
  if (error) return <div className="text-red-600 bg-red-50 border border-red-100 p-6 rounded-lg m-6">{error}</div>;

  // --- Core Financial Calculations ---
  // 1000: Cash | 1030: Inventory | 4000: Sales Revenue | 5000: COGS (if added)
  const totalCash = getBalance("1000");
  const totalInventory = getBalance("1030");
  const totalRevenue = getBalance("4000");
  
  // If you later add a specific Expense/COGS account, you can subtract it here
  const totalExpenses = getBalance("5000"); 
  const netProfit = totalRevenue - totalExpenses;

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-8">
      
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-gray-900 tracking-tight">Financial Overview</h1>
        <p className="text-gray-500 mt-1">Real-time balances, automated by Heaven Autos ERP.</p>
      </div>

      {/* KPI Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        
        {/* Cash Balance Card */}
        <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm flex items-center gap-4">
          <div className="p-4 bg-emerald-50 text-emerald-600 rounded-lg">
            <FiDollarSign className="w-8 h-8" />
          </div>
          <div>
            <p className="text-gray-500 text-sm font-medium">Available Cash</p>
            <h3 className="text-2xl font-bold text-gray-900">{totalCash.toLocaleString()} BDT</h3>
          </div>
        </div>

        {/* Inventory Value Card */}
        <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm flex items-center gap-4">
          <div className="p-4 bg-blue-50 text-blue-600 rounded-lg">
            <FiBox className="w-8 h-8" />
          </div>
          <div>
            <p className="text-gray-500 text-sm font-medium">Total Inventory Value</p>
            <h3 className="text-2xl font-bold text-gray-900">{totalInventory.toLocaleString()} BDT</h3>
          </div>
        </div>

        {/* Sales Revenue Card */}
        <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm flex items-center gap-4">
          <div className="p-4 bg-amber-50 text-amber-600 rounded-lg">
            <FiActivity className="w-8 h-8" />
          </div>
          <div>
            <p className="text-gray-500 text-sm font-medium">Total Sales Revenue</p>
            <h3 className="text-2xl font-bold text-gray-900">{totalRevenue.toLocaleString()} BDT</h3>
          </div>
        </div>

        {/* Net Profit Card */}
        <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm flex items-center gap-4">
          <div className="p-4 bg-indigo-50 text-indigo-600 rounded-lg">
            <FiTrendingUp className="w-8 h-8" />
          </div>
          <div>
            <p className="text-gray-500 text-sm font-medium">Net Profit Margin</p>
            <h3 className="text-2xl font-bold text-gray-900">{netProfit.toLocaleString()} BDT</h3>
          </div>
        </div>
      </div>

      {/* Automated Ledger / Transaction History */}
      <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
        <div className="p-6 border-b border-gray-200">
          <h2 className="text-xl font-bold text-gray-900">Recent Automated Transactions</h2>
          <p className="text-sm text-gray-500 mt-1">Journal entries automatically generated by system actions.</p>
        </div>
        
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse text-sm">
            <thead>
              <tr className="bg-gray-50 text-gray-600 border-b border-gray-200 font-semibold">
                <th className="p-4">Date</th>
                <th className="p-4">Description</th>
                <th className="p-4">Debits / Credits</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {journalEntries.slice(0, 10).map((entry) => (
                <tr key={entry.id} className="hover:bg-gray-50 transition bg-white">
                  <td className="p-4 whitespace-nowrap text-gray-600">
                    {entry.date}
                  </td>
                  <td className="p-4">
                    <span className="font-medium text-gray-900">{entry.description}</span>
                    <div className="text-xs text-gray-500 mt-1">
                      {entry.purchase ? `Purchase ID: ${entry.purchase}` : entry.sale ? `Sale ID: ${entry.sale}` : "Manual Entry"}
                    </div>
                  </td>
                  <td className="p-4">
                    <div className="space-y-1.5">
                      {entry.items.map((item) => (
                        <div key={item.id} className="text-sm flex items-center gap-2 font-medium">
                          {parseFloat(item.debit) > 0 ? (
                            <span className="text-emerald-600 flex items-center gap-1">
                              <FiArrowLeft className="w-3.5 h-3.5"/> + {item.debit} <span className="text-gray-500 font-normal ml-1">({item.account_name})</span>
                            </span>
                          ) : (
                            <span className="text-red-600 flex items-center gap-1">
                              <FiArrowRight className="w-3.5 h-3.5"/> - {item.credit} <span className="text-gray-500 font-normal ml-1">({item.account_name})</span>
                            </span>
                          )}
                        </div>
                      ))}
                    </div>
                  </td>
                </tr>
              ))}
              {journalEntries.length === 0 && (
                <tr>
                  <td colSpan="3" className="p-8 text-center text-gray-500 bg-white">
                    No transactions yet. Go make a purchase or sale!
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
}