# Generated by Django 6.0.6 on 2026-06-24 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('joining_date', models.DateField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='employee_pics/')),
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('age', models.IntegerField()),
                ('religion', models.CharField(max_length=50)),
                ('birth_id_no', models.CharField(blank=True, max_length=50)),
                ('nid_no', models.CharField(max_length=50, unique=True)),
                ('passport_no', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(default='Bangladeshi', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile1', models.CharField(max_length=15, unique=True)),
                ('mobile2', models.CharField(blank=True, max_length=15)),
                ('mobile_father', models.CharField(blank=True, max_length=15)),
                ('mobile_mother', models.CharField(blank=True, max_length=15)),
                ('mobile_others', models.CharField(blank=True, max_length=15)),
                ('acc_name', models.CharField(blank=True, max_length=100)),
                ('acc_no', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('bkash_no', models.CharField(blank=True, max_length=15)),
                ('nagad_no', models.CharField(blank=True, max_length=15)),
                ('rocket_no', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('institute_name', models.CharField(max_length=200)),
                ('passing_year', models.IntegerField()),
                ('group', models.CharField(max_length=100)),
                ('gpa', models.CharField(max_length=10)),
                ('board_university', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='person.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('shop_name', models.CharField(blank=True, help_text='Leave blank if retail customer', max_length=200)),
                ('proprietor_name', models.CharField(max_length=200)),
                ('employee_name', models.CharField(blank=True, help_text='Employee acting for the shop/buyer', max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile1', models.CharField(max_length=15, unique=True)),
                ('mobile2', models.CharField(blank=True, max_length=15)),
                ('nid', models.CharField(blank=True, max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='customer_pics/')),
                ('country', models.CharField(default='Bangladesh', max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('police_station', models.CharField(blank=True, max_length=100)),
                ('post_office', models.CharField(blank=True, max_length=50)),
                ('town_village', models.CharField(max_length=100)),
                ('market_name', models.CharField(blank=True, max_length=200)),
                ('customer_type', models.CharField(choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale')], default='Retail', max_length=20)),
                ('referred_by', models.CharField(blank=True, max_length=100)),
                ('note_remarks', models.TextField(blank=True)),
                ('entry_date_time', models.DateTimeField(auto_now_add=True)),
                ('entry_by', models.ForeignKey(blank=True, help_text='Select the employee who added this record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_work', to='person.employee')),
            ],
        ),
    ]
