# Generated by Django 6.0.6 on 2026-06-09 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='entry_by',
            field=models.ForeignKey(blank=True, help_text='Select the employee who added this record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.employee'),
        ),
    ]
