# Generated by Django 6.0.6 on 2026-06-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='negotiated_price',
        ),
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Leave blank to use standard sale price, or enter a negotiated price.', max_digits=10),
            preserve_default=False,
        ),
    ]
