# Generated by Django 6.0.6 on 2026-06-22 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0004_alter_customer_id_alter_education_id_and_more'),
        ('purchase', '0003_remove_purchaseorder_discount_amount_and_more'),
        ('sale', '0003_remove_saleorder_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('payment_type', models.CharField(choices=[('IN', 'Payment Received (Sale)'), ('OUT', 'Payment Paid (Purchase)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank Transfer'), ('Bkash', 'bKash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket')], default='Cash', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Txn ID or Check Number', max_length=100, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.employee')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchase.purchaseorder')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sale.saleorder')),
            ],
        ),
    ]
